# Generated by Django 6.0.2 on 2026-03-05 02:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='finance.category')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='finance.workspace')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Month must be in format "YYYY-MM" (e.g. "2026-02").', regex='^\\d{4}-\\d{2}$')])),
                ('rule_type', models.CharField(choices=[('fixed', 'Fixed'), ('percent', 'Percent')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='finance.category')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='finance.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='AccountMonthConfig',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Month must be in format "YYYY-MM" (e.g. "2026-02").', regex='^\\d{4}-\\d{2}$')])),
                ('income_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_configs', to='finance.account')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_month_configs', to='finance.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='finance.workspace'),
        ),
        migrations.CreateModel(
            name='WorkspaceMember',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='editor', max_length=10)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='finance.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.CharField(max_length=255)),
                ('date', models.DateField(db_index=True)),
                ('type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.category')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'date'], name='idx_tx_workspace_date'), models.Index(fields=['workspace', 'category'], name='idx_tx_workspace_category'), models.Index(fields=['workspace', 'account'], name='idx_tx_workspace_account')],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['workspace'], name='idx_category_workspace'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('workspace', 'parent', 'name'), name='uniq_category_workspace_parent_name'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['workspace', 'month'], name='idx_budget_workspace_month'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('workspace', 'month', 'category'), name='uniq_budget_workspace_month_category'),
        ),
        migrations.AddIndex(
            model_name='accountmonthconfig',
            index=models.Index(fields=['workspace', 'month'], name='idx_amc_workspace_month'),
        ),
        migrations.AddConstraint(
            model_name='accountmonthconfig',
            constraint=models.UniqueConstraint(fields=('workspace', 'month', 'account'), name='uniq_amc_workspace_month_account'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['workspace'], name='idx_account_workspace'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='uniq_account_workspace_name'),
        ),
        migrations.AddIndex(
            model_name='workspacemember',
            index=models.Index(fields=['user_id'], name='idx_workspace_member_user'),
        ),
        migrations.AddConstraint(
            model_name='workspacemember',
            constraint=models.UniqueConstraint(fields=('workspace', 'user_id'), name='uniq_workspace_member'),
        ),
    ]
