# Generated by Django 6.0.2 on 2026-02-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_income_base_from_account_month_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmonthconfig',
            name='income_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
